version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: database-absence
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: absence
    ports:
      - "3307:3306"
    networks:
      - absence-net
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: employee-management-container
    restart: on-failure
    ports:
      - "8085:8080"
    depends_on:
      - db
    networks:
      - absence-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/absence?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
      - JWT_SECRET=mariCleSecreteTresSecurisee123456gestiondesabsencesprojetdemospringboot20010814
networks:
  absence-net:
    driver: bridge

volumes:
  db_data: