name: mra pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: build
        run: mvn clean compile
  version:
    needs: compile
    uses: ./.github/workflows/release-version.yml
    with:
      dry_run: true
    secrets: inherit
  security-scan:
    needs: version
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/security-scan.yml
    secrets: inherit

  sonar-analysis:
    if: github.ref == 'refs/heads/main'
    needs: version
    uses: ./.github/workflows/sonar-analyze.yml
    secrets: inherit
    with:
      app_version: ${{ needs.version.outputs.new_version }}

  semantic-versioning:
    needs: [security-scan, sonar-analysis]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release-version.yml
    with:
      dry_run: false
    secrets: inherit
