name: Pipeline
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
# compiler le code --> feature (uniquement) wla pull request
permissions:
  contents: write
  packages: write
  security-events: write
  actions: read

jobs:
  semantic-versioning:
    uses: ./.github/workflows/release-version.yml
    secrets: inherit

  source-code-scan:
    uses: ./.github/workflows/security-scan.yml
    secrets: inherit
  sonar-analysis:
    needs: [ semantic-versioning ]
    uses: ./.github/workflows/sonar-analyze.yml
    secrets: inherit

    with:
      app_version: ${{ needs.semantic-versioning.outputs.new_tag }}


  build-and-deploy:
    needs: [sonar-analysis, source-code-scan, semantic-versioning]
    runs-on: ubuntu-latest
    env:
        APP_VERSION: ${{ needs.semantic-versioning.outputs.new_tag }}
    steps:
         - name: checkout code
           uses: actions/checkout@v4
           with:
             fetch-depth: 0
             token: ${{ secrets.GITHUB_TOKEN }}

         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
               java-version: '21'
               distribution: 'temurin'
               cache: maven
         - name: update maven project version
           run: mvn versions:set -DnewVersion=${{ env.APP_VERSION }} -DgenerateBackupPoms=false
         - name: Commit and Push pom.xml update
           run: |
               git config --global user.name "github-actions[bot]"
               git config --global user.email "github-actions[bot]@users.noreply.github.com"
               git add pom.xml
               git diff --quiet && git diff --staged --quiet || (git commit -m "chore: bump version to ${{ env.APP_VERSION }} [skip ci]" && git push)

