name: Pipeline
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  employeemanagement-backend
  CONTAINER_NAME: employee-management-container
  SONAR_PROJECT_KEY: Mariamyammoun_EmployeeManagement
  SONAR_ORG_KEY: mariamyammoun

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  call-versioning:
    uses: ./.github/workflows/release-version.yml
    secrets: inherit

  build-and-deploy:
      needs: call-versioning
      runs-on: ubuntu-latest
      env:
        APP_VERSION: ${{ needs.call-versioning.outputs.new_tag }}

      steps:
         - name: checkout code
           uses: actions/checkout@v4
           with:
             fetch-depth: 0

         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
               java-version: '21'
               distribution: 'temurin'
               cache: maven
         - name: update maven project version
           run: mvn versions:set -DnewVersion=${{ env.APP_VERSION }} -DgenerateBackupPoms=false
         - name: Build and Analyze with SonarCloud
           env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           run: |
               mvn -B verify sonar:sonar \
                 -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}} \
                 -Dsonar.organization=${{env.SONAR_ORG_KEY}} \
                 -Dsonar.host.url=https://sonarcloud.io \
                 -Dsonar.projectVersion=${{ env.APP_VERSION }} \
                 -Dsonar.branch.name=${{ github.ref_name }}

         - name: Build Docker Image
           run: |
             docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }} .

         - name: Run Trivy Security Scan
           uses: aquasecurity/trivy-action@master
           with:
             image-ref: '${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}'
             format: 'table'
             severity: 'CRITICAL,HIGH'
             exit-code: '1'
