name: mra pipeline
on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
    contents: write
    security-events: write
    actions: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: build
        run: mvn clean compile
  security-scan:
    needs: compile
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/security-scan.yml
    secrets: inherit

  semantic-versioning:
    needs: security-scan
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release-version.yml
    secrets: inherit

#  sonar-analysis:
#    if: github.ref == 'refs/heads/main'
#    needs: [ semantic-versioning ]
#    uses: ./.github/workflows/sonar-analyze.yml
#    secrets: inherit
#    with:
#      app_version: ${{ needs.semantic-versioning.outputs.new_tag }}

  deploy-dev:
    needs: [ semantic-versioning ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development
    env:
      APP_VERSION: ${{ needs.semantic-versioning.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: update version
        run: mvn versions:set -DnewVersion=${{ env.APP_VERSION }} -DgenerateBackupPoms=false
      - name: Package Application
        run: mvn clean package -DskipTests
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
