name: Pipeline
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  semantic-versioning:
    uses: ./.github/workflows/release-version.yml
    secrets: inherit

  build-and-deploy:
      needs: semantic-versioning
      runs-on: ubuntu-latest
      env:
        APP_VERSION: ${{ needs.semantic-versioning.outputs.new_tag }}
      steps:
         - name: checkout code
           uses: actions/checkout@v4
           with:
             fetch-depth: 0

         - name: Set up JDK 21
           uses: actions/setup-java@v4
           with:
               java-version: '21'
               distribution: 'temurin'
               cache: maven
         - name: update maven project version
           run: mvn versions:set -DnewVersion=${{ env.APP_VERSION }} -DgenerateBackupPoms=false
         - name: Build and Analyze with SonarCloud
           env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               SONAR_TOKEN: ${{ secrets.authGithub  }}
           run: |
               mvn -B verify sonar:sonar \
                 -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
                 -Dsonar.organization=${{ vars.SONAR_ORG_KEY }} \
                 -Dsonar.host.url=https://sonarcloud.io \
                 -Dsonar.projectVersion=${{ env.APP_VERSION }} 
              

         - name: Build Docker Image
           run: |
             docker build -t ${{ vars.REGISTRY }}/${{ vars.OWNER_LC }}/${{ vars.IMAGE_NAME }}:${{ env.APP_VERSION }} .

         - name: scan security trivy
           uses: aquasecurity/trivy-action@master
           with:
             image-ref:  '${{ vars.REGISTRY }}/${{ vars.OWNER_LC }}/${{ vars.IMAGE_NAME }}:${{ env.APP_VERSION }}'
             format: 'table'
             severity: 'CRITICAL,HIGH'
             exit-code: '0'

         - name: Login to GitHub Container Registry
           uses: docker/login-action@v3
           with:
               registry: ${{ vars.REGISTRY }}
               username: ${{ github.actor }}
               password: ${{ secrets.GITHUB_TOKEN }}
         - name: Push Docker Image
           run: |
             docker push ${{ vars.REGISTRY }}/${{ vars.OWNER_LC }}/${{ vars.IMAGE_NAME }}:${{ env.APP_VERSION }}
             docker tag ${{ vars.REGISTRY }}/${{ vars.OWNER_LC }}/${{ vars.IMAGE_NAME }}:${{ env.APP_VERSION }} ${{ vars.REGISTRY }}/${{ vars.OWNER_LC }}/${{ vars.IMAGE_NAME }}:latest
             docker push ${{ vars.REGISTRY }}/${{ vars.OWNER_LC }}/${{ vars.IMAGE_NAME }}:latest
